version: '3.9'
services:

  hivemq:
    image: hivemq/hivemq4
    restart: always
    ports:
      - 1884:1883

  kafka-zookeeper:
    image: johnnypark/kafka-zookeeper
    restart: always
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: 127.0.0.1
      NUM_PARTITIONS: 10

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
